### ISSUE TITLE
Published Cargo out of date? (undeclared identifier 'nullptr' when building)

### ISSUE THREAD

**Issue by robertpyke** [Noxime/steamworks-rs#76]
Hi,

when I try to build with v0.7 as a dependency on my m1 Mac, I get errors about undeclared identifier 'nullptr':

```
[dependencies]
...
steamworks = "0.7.0"
```

```
robertpyke@Roberts-Mac-mini RustyTower % STEAM_SDK_LOCATION=~/Documents/dev/git/RustyTower/sdk/151 cargo build
   Compiling rusty-tower v0.1.0 (/Users/robertpyke/Documents/dev/git/RustyTower)
   Compiling steamworks-sys v0.7.0
error: failed to run custom build command for `steamworks-sys v0.7.0`

Caused by:
  process didn't exit successfully: `/Users/robertpyke/Documents/dev/git/RustyTower/target/debug/build/steamworks-sys-039c9649e303658a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/redistributable_bin/osx
  cargo:rustc-link-lib=dylib=steam_api

  --- stderr
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_common.h:227:54: error: use of undeclared identifier 'nullptr'
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_common.h:227:63: error: use of undeclared identifier 'nullptr'
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:87:11: error: use of undeclared identifier 'nullptr'
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:88:11: error: use of undeclared identifier 'nullptr'
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:147:12: error: use of undeclared identifier 'nullptr'
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:147:31: error: use of undeclared identifier 'nullptr'
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_common.h:227:54: error: use of undeclared identifier 'nullptr', err: true
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_common.h:227:63: error: use of undeclared identifier 'nullptr', err: true
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:87:11: error: use of undeclared identifier 'nullptr', err: true
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:88:11: error: use of undeclared identifier 'nullptr', err: true
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:147:12: error: use of undeclared identifier 'nullptr', err: true
  /Users/robertpyke/Documents/dev/git/RustyTower/sdk/151/public/steam/steam_api_internal.h:147:31: error: use of undeclared identifier 'nullptr', err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /Users/robertpyke/.cargo/registry/src/github.com-1ecc6299db9ec823/steamworks-sys-0.7.0/build.rs:49:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I then change that to use the git repo directly: 

```
[dependencies]
...
steamworks = {git = "https://github.com/Noxime/steamworks-rs"}
```

the build passes without issue.

I also tried cloning this repo directly onto my machine and running the chat-example. That worked when referencing the git repo code, but hit the same issue when building against latest cargo release.

I just wanted to check if I'm missing something, or if the published cargo release just needs to be updated?

**Comment by Noxime** [comment]
I've gone and updated crates to 0.8.0!
